// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'production_detail_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProductionDetailModel _$ProductionDetailModelFromJson(
        Map<String, dynamic> json) =>
    ProductionDetailModel(
      lineCd: json['lineCd'] as String,
      lineName: json['lineName'] as String,
      pkCd: json['pkCd'] as String,
      planDate: json['planDate'] as String,
      planStartTime: json['planStartTime'] as String,
      as400PlantAmt: (json['as400PlantAmt'] as num).toInt(),
      teamName: json['teamName'] as String,
      shiftPeriodName: json['shiftPeriodName'] as String,
      shiftPeriod: json['shiftPeriod'] as String,
      b1: json['b1'] as String,
      b2: json['b2'] as String,
      b3: json['b3'] as String,
      b4: json['b4'] as String,
      ot: json['ot'] as String,
      modelCd: json['modelCd'] as String,
      productCd: json['productCd'] as String,
      partNo: json['partNo'] as String,
      partUpper: json['partUpper'] as String,
      partLower: json['partLower'] as String,
      cycleTime: json['cycleTime'] as String,
      manPower: (json['manPower'] as num).toInt(),
      planTotalTime: (json['planTotalTime'] as num).toInt(),
      planFgAmt: (json['planFgAmt'] as num).toInt(),
      operator: (json['operator'] as num).toInt(),
      leader: (json['leader'] as num).toInt(),
      status: json['status'] as String,
      statusName: json['statusName'] as String,
      updatedBy: json['updatedBy'] as String,
      updatedDate: json['updatedDate'] as String,
      id: (json['id'] as num).toInt(),
      actualStartDt: json['actualStartDt'] as String,
      actualStopDt: json['actualStopDt'] as String,
      actualTotalTime: (json['actualTotalTime'] as num).toInt(),
      setupTime: (json['setupTime'] as num).toInt(),
      actualFgAmt: (json['actualFgAmt'] as num).toInt(),
      okAmt: (json['okAmt'] as num).toInt(),
      ngAmt: (json['ngAmt'] as num).toInt(),
      as400ProductCD: json['as400ProductCD'] as String,
    );

Map<String, dynamic> _$ProductionDetailModelToJson(
        ProductionDetailModel instance) =>
    <String, dynamic>{
      'lineCd': instance.lineCd,
      'lineName': instance.lineName,
      'pkCd': instance.pkCd,
      'planDate': instance.planDate,
      'planStartTime': instance.planStartTime,
      'as400PlantAmt': instance.as400PlantAmt,
      'teamName': instance.teamName,
      'shiftPeriodName': instance.shiftPeriodName,
      'shiftPeriod': instance.shiftPeriod,
      'b1': instance.b1,
      'b2': instance.b2,
      'b3': instance.b3,
      'b4': instance.b4,
      'ot': instance.ot,
      'modelCd': instance.modelCd,
      'productCd': instance.productCd,
      'partNo': instance.partNo,
      'partUpper': instance.partUpper,
      'partLower': instance.partLower,
      'cycleTime': instance.cycleTime,
      'manPower': instance.manPower,
      'planTotalTime': instance.planTotalTime,
      'planFgAmt': instance.planFgAmt,
      'operator': instance.operator,
      'leader': instance.leader,
      'status': instance.status,
      'statusName': instance.statusName,
      'updatedBy': instance.updatedBy,
      'updatedDate': instance.updatedDate,
      'id': instance.id,
      'actualStartDt': instance.actualStartDt,
      'actualStopDt': instance.actualStopDt,
      'actualTotalTime': instance.actualTotalTime,
      'setupTime': instance.setupTime,
      'actualFgAmt': instance.actualFgAmt,
      'okAmt': instance.okAmt,
      'ngAmt': instance.ngAmt,
      'as400ProductCD': instance.as400ProductCD,
    };
